export enum ComponentType {
    Position = 'position',
    Velocity = 'velocity',
    Rotation = 'rotation',
    Mesh = 'mesh',
    Input = 'input',
    Health = 'health',
    Damage = 'damage',
    DamageFlash = 'damage-flash',
    Hurtbox = 'hurtbox',
    Hitbox = 'hitbox',
    Lifespan = 'lifespan',
    HealthBar = 'healthbar',
    Visual = 'visual',
    Direction = 'direction',
    Impulse = 'impulse',
    SpriteAnimation = 'sprite-animation',
    AI = 'ai',
}
